spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: postgres
    password: apxmfh123@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
